spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        default_schema: esteban
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521/xepdb1 # Cambiado el URL para Oracle
    username: esteban # Cambiado el nombre de usuario
    password: gc999 # Cambiada la contraseña
    driver-class-name: oracle.jdbc.OracleDriver # Cambiado el nombre del controlador

    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

  messages:
    basename: bundles/apiLanguageBundle

ssmu-api:
  openapi:
    dev-url: http://localhost:8080/ssmu-api
    prod-url: https://ssmu-api.com

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

# Server properties
server:
  servlet:
    context-path: /ssmu-api
  port: 8080
